// src/lib/common/Chip/Chip.svelte
<script lang="ts">
  import { compactMode } from '$stores/compactMode';
  import { themeMode } from '$stores/themeMode';
  import { theme, type colorShade as colorShadeType, type colorType } from '$utils/theme/theme';
  import Color from 'color';
  import { Button } from 'fluent-svelte';

  export let href: string | undefined = undefined;
  export let compact = $compactMode;

  export let color: colorType = 'green';
  export let shade: { dark: colorShadeType; light: colorShadeType } = { dark: 300, light: 800 };
  $: themeColor =
    color === 'neutral' ? theme($themeMode).color.neutral[$themeMode] : theme($themeMode).color[color];
  $: colorShade = (() => {
    if (color === 'neutral') return 1200;
    return $themeMode === 'light' ? shade.light : shade.dark;
  })();
</script>

<Button
  {href}
  tabIndex={href ? 0 : -1}
  variant="hyperlink"
  style="
    height: {compact ? 24 : 30}px;
    color: currentColor;
    font-size: 0.75rem;
    padding: 0 {compact ? 6 : 10}px;
    cursor: default;
    font-size: 13px;
    color: var(--color-{color}{color === 'neutral' ? `-${$themeMode}` : ''}-{colorShade});
    box-shadow: {Color(themeColor[colorShade]).alpha(0.14).string()} 0px 0px 0px 1.25px inset;
    --fds-subtle-fill-transparent: {color === 'neutral'
    ? 'transparent'
    : Color(themeColor[colorShade]).alpha(0.05).string()};
    --fds-subtle-fill-secondary: {href
    ? Color(themeColor[colorShade]).alpha(0.11).string()
    : `var(--fds-subtle-fill-transparent)`};
    --fds-subtle-fill-tertiary: {href
    ? Color(themeColor[colorShade]).alpha(0.17).string()
    : `var(--fds-subtle-fill-transparent)`};
    white-space: nowrap;
    {$$restProps['style']}
  "
  {...$$restProps}
>
  <slot />
</Button>

// src/components/Chip/Chip.tsx
import { useTheme, type SerializedStyles } from '@emotion/react';
import styled from '@emotion/styled';
import Color from 'color';
import type { colorType, themeType } from '../../utils/theme/theme';
import { buttonEffect } from '../Button/buttonEffect';

interface IStyledChip {
  color: colorType;
  //colorShade: colorShade;
  theme: themeType;
  isClickable: boolean;
  cssExtra?: SerializedStyles;
}

const StyledChip = styled.span<IStyledChip>`
  ${({ color, theme, isClickable }) =>
    isClickable ? buttonEffect(color, theme.mode === 'light' ? 800 : 200, theme) : null};
  border: none !important;
  background: ${({ theme, color }) =>
    color === 'neutral'
      ? 'transparent'
      : Color(theme.color[color][theme.mode === 'light' ? 800 : 300])
          .alpha(0.05)
          .string()};
  display: inline-flex;
  height: 1.25rem;
  align-items: center;
  justify-content: center;
  padding: 0 0.375rem;
  margin: 2px;
  font-family: ${({ theme }) => theme.font.detail};
  font-size: 0.75rem;
  font-weight: 500;
  white-space: nowrap;
  display: inline-flex;
  box-shadow: ${({ theme, color }) =>
      color === 'neutral'
        ? Color(theme.color[color][theme.mode][1200]).alpha(0.25).string()
        : Color(theme.color[color][theme.mode === 'light' ? 800 : 300])
            .alpha(0.1)
            .string()}
    0px 0px 0px 1.25px inset !important;
  border-radius: ${({ theme }) => theme.radius};
  color: ${({ theme, color }) =>
    color === 'neutral'
      ? Color(theme.color[color][theme.mode][1200]).string()
      : Color(theme.color[color][theme.mode === 'light' ? 800 : 300]).string()};
  ${({ cssExtra }) => (cssExtra ? cssExtra : null)};
`;

interface IChip {
  label: string;
  color?: colorType;
  onClick?: () => void;
  cssExtra?: SerializedStyles;
}

function Chip(props: IChip) {
  const theme = useTheme() as themeType;

  return (
    <StyledChip
      onClick={props.onClick}
      theme={theme}
      color={props.color ? props.color : 'neutral'}
      isClickable={props.onClick ? true : false}
      cssExtra={props.cssExtra}
    >
      {props.label}
    </StyledChip>
  );
}

export { Chip };
